version: '3.9'

services:
  api:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    networks:
      - custom_network
    ports:
      - "8000:8000"
    restart: always

  db:
    image: postgres:15
    env_file:
      - .env
    networks:
      - custom_network
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "task-tracker-db:/var/lib/postgresql/data"


networks:
  custom_network:
    name: custom_network

volumes:
  task-tracker-db:
